### ISSUE TITLE
Can not connect esp to AP ssid with space.

### ISSUE THREAD

**Issue by tinamore** [martin-ger/esp_wifi_repeater#108]
Hi,

When i connect ESP to ssid "ABC  XYZ" then
..........................
no ABC+XYZfound, reconnect after 1s
disconnect from ssid ABC+XYZ, reason 201
reconnect
..........................
I think when submit post value form html then convert space " " to "+".
Has anyone get this error?

**Comment by martin-ger** [comment]
Write "ABC\ XYZ" instead.

**Comment by marek26340** [comment]
Or "ABC%20XYZ".

**Comment by tinamore** [comment]
"ABC\ XYZ" => not working , I still see ABC+XYZ
"ABC%20XYZ" => ABC XYZ. Solved the problem.

Thanks for reply.
