### ISSUE TITLE
voltage monitoring

### ISSUE THREAD

**Issue by geofrancis** [martin-ger/esp_wifi_repeater#11]
would you be able to impliment battery monitoring so it could deep sleep if the battery gets low and power up when the battery has charge?

**Comment by jymcd** [comment]
why not use a battery protection board for the type of battery you are using. most have charging circuitry as well as over voltage/current and under voltage/current protection and you would not need to manually monitor the battery.

**Comment by martin-ger** [comment]
added power management features -> see README. Default is off.
