### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by lupus78** [martin-ger/esp_wifi_repeater#115]
In the readme, the command to flash the firmware for Wemos D1 is wrong.

This is the wrong command:
`esptool.py --port /dev/ttyUSB0 write_flash -fs 32MB 0x00000 firmware/0x00000.bin 0x10000 firmware/0x10000.bin`

he 32MB is clearly worng, that should be 32m, but actually that is deprecated, it should be now 4MB
and also for me I needed a few extra paramteres to make it work, so this is the command which worked for me:
`esptool.py --port /dev/ttyUSB0 write_flash -fs 4MB -ff 80m -fm dio 0x00000 firmware/0x00000.bin 0x10000 firmware/0x10000.bin`

**Comment by martin-ger** [comment]
Thanks - changed that.
