### ISSUE TITLE
Port Forwarding ?

### ISSUE THREAD

**Issue by timpur** [martin-ger/esp_wifi_repeater#13]
Wondering if its possible to configure port forwarding? 
( My router doesn't allow me to add routes... so kinda need this if i want to connect to a device on this extended wifi network)

**Comment by martin-ger** [comment]
Added port forwarding. Look for the command "portmap add [TCP|UDP] <ext port> <int IP> <int port>.

**Comment by timpur** [comment]
Awesome :)
Sorry.
