### ISSUE TITLE
Doubt.

### ISSUE THREAD

**Issue by genoinosonda** [martin-ger/esp_wifi_repeater#130]
First of all I would like to thank you for the excellent work being done by the community, without doubt one of the most complete and most beneficial ones I have ever encountered for esp8226 mesh.

But I did not understand something reminiscent of ESP. I'm trying to play this firmware inside a board (it worked perfectly) and at the same time I would like to compile a stekch through arduino's IDE.

Would it be possible?

The result would be a mesh network with several ESP8266 reading the dht22 and creating POST packets and sending to an API.

Remembering that only one node would know the WAN, the other only LAN.

Many thanks, hugs.

**Comment by martin-ger** [comment]
Short answer: Would it be possible? No.

Longer version: My code is pure C and it doesn't compile in Arduino. Also, it requires a special version of the esp-opwn-lwip. Guess, it can be wrapped somehow and the Arduino environment can be patched to use the other lib, but requires work. 

The other option would be, to integrate additional (sensoring) functionality into the existing code using C and the SDK API. I already started with that by adding GPIO input and output via MQTT. Can be enabled by compiling with the symbols USER_GPIO_IN and USER_GPIO_OUT defined. In a similar way, other sensoring code and also HTTP POSTs could be integrated.
