### ISSUE TITLE
Quick Questions

### ISSUE THREAD

**Issue by philippd1** [martin-ger/esp_wifi_repeater#131]
Hey Martin,
first of all thank you for your time and effort you put in this project.
I've got some questions:
1) how does the standard repeating work? by bssid or essid?
2) What happens if more than 8 meshed units are in a room (simplification)? Is the 9th then "stupid" and repeats like a non-meshed would?

Best regards

**Comment by martin-ger** [comment]
Let me try to answer:
1. It is an infrastructure network with AP, so it is actually the ESSID. I wrote BSSID in the Readme, but this is actually wrong. Will fix that in the next version.
2. 9 meshed in a room will most probably all try to connect to the same uplink AP, as they will all see the same AP with the lowest mesh level. If more than 8 want to connect to the same AP (and this an ESP that doesn't allow for 9 clients), then the 9th will fail to connect. There is no mechanism other than scan again and try again.
