### ISSUE TITLE
Feature request: force connect to an uplink AP right now with auto_connect disabled

### ISSUE THREAD

**Issue by marek26340** [martin-ger/esp_wifi_repeater#134]
Hello. If you will set the repeater not to try again to find the uplink AP (set auto_connect 0), what if I want to force the ESP to do a search of available APs and connect to the uplink AP if found and I do not want to reset the ESP? The CLI command might look like "sta_connect" or something like that...

**Comment by martin-ger** [comment]
done: try "connect" and "disconnect"
