### ISSUE TITLE
Spaces don't work in WIFI station names

### ISSUE THREAD

**Issue by jcea** [martin-ger/esp_wifi_repeater#154]
I just tried to "join" a network with a space in the WIFI network name. That space, using the web configuration interface, is replaced with a "+", following HTTP specs. This project should replace "+" as "space" internally.

Currently, I can NOT join this network, with spaces in the name.

Thanks!.

**Comment by martin-ger** [comment]
On the CLI use '\ " instead.


Am 6. März 2018 12:35:54 vorm. schrieb jcea <notifications@github.com>:

**Comment by marek26340** [comment]
I remember that only "\ " and "%20" make a space...

**Comment by martin-ger** [comment]
If you want to enter non-ASCII or special characters in the web interface you have to use HTTP-style hex encoding like "My%20AccessPoint". This will result in a string "My AccessPoint". With this hex encoding you can enter any byte value you like, except for 0 (for C-internal reasons).
