### ISSUE TITLE
Feature Request: Allow configuration of MAX_CLIENTS

### ISSUE THREAD

**Issue by computersmith64** [martin-ger/esp_wifi_repeater#155]
Hi - great project! I have flashed it onto a Wemos D1 R2 & it works great, but I have a use case where I want to be able to limit the number of client connections. I notice that user_config.h has a MAX_CLIENTS defined & user_main.c uses it, so I'm wondering if you could either put a parameter in the web config tool or put a command line setting so that it can be changed?

Thanks!

**Comment by martin-ger** [comment]
Can do this - will be added in the next version.

**Comment by computersmith64** [comment]
Awesome - thank you! Any idea when this will be?

**Comment by martin-ger** [comment]
Has been added, try:
```
set max_clients 5
save
reset
```
