### ISSUE TITLE
AP reconnect to hidden SSID failure

### ISSUE THREAD

**Issue by froido** [martin-ger/esp_wifi_repeater#167]
Hi together,

thanks for this amazing work! The Mesh is working absolutely accurate and stable for the first weeks. All SSIDs of the network are hidden (mesh and ap). Restarting of the ESPs is no problem, it will always connect to the hidden AP again.

After restarting the AP (AVM FritzBox), the ESP is no longer able to find the APs Wi-Fi. It says:
> No AP with ssid smarthome found
> scandone

Setting the SSID at the AP to visible helps. The ESP connects immediately to the AP.

I noticed that my ESP sensors, are connecting to the AP even after restarting it.

I do not want to broadcast the SSID of the network. Neither do I want to switch the SSID to visible after a restart of the AP. Especially as I normally do not recognize a restart of the AP. Any idea how to fix this? 

Thanks a lot in advance!
Sven

**Comment by martin-ger** [comment]
Automesh relies on a "manual" scan for APs - this only works with non-hidden SSIDs, as it looks for the beacons, these beacons are not send, when an AP is hidden. 

Connecting to a hidden SSID works different: it sends out a "Probe request" and receives a "Probe response" from the hidden AP (with this message it is actually no longer "hidden").

If you want to work with hidden SSIDs, disable automesh and configure the ESP manually - this should work.
