### ISSUE TITLE
Random Flickering Blue Light

### ISSUE THREAD

**Issue by ram1505** [martin-ger/esp_wifi_repeater#17]
Hi,
I did everything as per the steps mentioned. Here is my user_config.h file. When I flash the firmware and reboot the esp, the ESP blue LED flickers rapidly. When I connect to Arduino IDE serial 115200 baud, I get gibberish dump. What am I doing wrong?

#ifndef _USER_CONFIG_
#define _USER_CONFIG_

typedef enum {SIG_DO_NOTHING=0, SIG_START_SERVER=1, SIG_SEND_DATA, SIG_UART0, SIG_CONSOLE_RX, SIG_CONSOLE_TX, SIG_PACKET } USER_SIGNALS;

#define WIFI_SSID            "MyWiFiSSID"
#define WIFI_PASSWORD        "MyWiFiPassword"

#define WIFI_AP_SSID         "RangeExtenderAP"
#define WIFI_AP_PASSWORD     "none"

#define MAX_CLIENTS	     8
#define MAX_DHCP	     8

//
// Size of the console buffers
//
#define MAX_CON_SEND_SIZE    1024
#define MAX_CON_CMD_SIZE     80

//
// Define this if you have a status LED connected to GPIO LED_NO
//
#define STATUS_LED      1
#define LED_NO		2

// Select the GPIO init function according to your selected GPIO
//#define SET_LED_GPIO	PIN_FUNC_SELECT(PERIPHS_IO_MUX_U0TXD_U, FUNC_GPIO1)
#define SET_LED_GPIO	PIN_FUNC_SELECT(PERIPHS_IO_MUX_GPIO2_U, FUNC_GPIO2)
//#define SET_LED_GPIO	PIN_FUNC_SELECT (PERIPHS_IO_MUX_MTDI_U, FUNC_GPIO4)

//
// Define this to support the "scan" command for AP search
//
#define ALLOW_SCANNING      1

//
// Define this to support the "sleep" command for power management and deep sleep
// Requires a connection of GPIO16 and RST (probably not availabe on ESP01 modules)
//
#define ALLOW_SLEEP         1

//
// Define this if you want to have access to the config console via TCP.
// Ohterwise only local access via serial is possible
//
#define REMOTE_CONFIG      1
#define CONSOLE_SERVER_PORT  7777

//
// Define this if you want to offer monitoring access to all transmitted data between the soft AP and all STAs.
// Packets are mirrored in pcap format to the given port.
// CAUTION: this might be a privacy issue!!!
//
#define REMOTE_MONITORING  1

#define MONITOR_BUFFER_SIZE 0x3c00

// Define this if you want to cut packets short in case of too high data rate
#define MONITOR_BUFFER_TIGHT 0x1000

// Define this if you want to silently drop any packet that cannot be send to the monitor
//#define DROP_PACKET_IF_NOT_RECORDED 1

#endif

**Comment by martin-ger** [comment]
Do you use an ESP-01 module? Try to compile it with SDK 1.5.4. this works for me.

**Comment by ram1505** [comment]
Yes I tried it on ESP-01. How do I compile with SDK 1.5.4?

**Comment by martin-ger** [comment]
Switch in the Makefile of esp-open-sdk to:
VENDOR_SDK = 1.5.4

You can get the SDK from:
http://bbs.espressif.com/download/file.php?id=1469&sid=9c7919d26a8c0bacacd54c5168d0b698

First you can test the firmware by flashing my precompiled images from the firmware_1.5.4 directory.

**Comment by ram1505** [comment]
Will do and update. Thanks

**Comment by ram1505** [comment]
Tried your 1.5.4 bin files and it worked perfectly. Gonna recompile 1.5.4 and try with my settings and see if it works well. Will keep you posted.

**Comment by ram1505** [comment]
Hey, I recompile to 1.5.4 and tried to flash again. When I Compile the firmware files, it always creates 0x00000 and 0x10000. However, 1.5.4 looks for 0x40000. I made the necessary changes I clouding my wifi details and flashed to esp successfully. When I open the serial window, I can now see the status of connectivity however, it always keeps saying trying to connect. What's going wrong?

**Comment by martin-ger** [comment]
That is the normal behavior when it cannot establish the connection. "show" gives you the right parameters? Can you connect to the esp's AP? Try to edit the params via the commandline (serial or wifi over the stationAP) and then "save" and "reset".

**Comment by ram1505** [comment]
What can I say martin. Simply Awesome! It works perfectly with 1.5.4. I managed to telnet to the ESP nd changed the parameters too. Thank you so much. You have a great weekend man. Cheers!

**Comment by ram1505** [comment]
I've my Raspberry Pi set as Access point with the following: inet addr:172.24.1.1  Bcast:172.24.1.255  Mask:255.255.255.0. I am trying to use the ESP to range extend for the Pi. By default, the firmware sets the ESP to 192.168.4.1 for router access and 192.168.4.2 for network access. I noticed that when I telnet to ESP and type set network ip-addr where I can define a IP range like 172.24.1.0 and ESP can then be booted with this network range. I can successfully connect my ESP to my RPi AP's SSID. However, both these devices seems to be in different subnet. How can I make these 2 devices to be on same subnet so that I can use the network access via ESP to access a webserver running on Raspberry Pi (for instance at 172.24.1.1/index.html?

**Comment by martin-ger** [comment]
As the ESP works as NAT-router, the AP interface and the STA interface of the ESP must be in different subnets (I first tried to make it work as a real layer 2 repeater, however this fails, as the closed WiFi-routines do not allow for sending the required frames).

From the AP-side (network 192.168.4.x) of the ESP you can transparently connect to the outside networks (e.g. 172.24.1.1.) and the Internet. So, a station connected to the range extending ESP network (e.g. a node 192.168.4.3) should be able  to connect to 172.24.1.1 without any problems (given that it is configured via DHCP and has received the ESP as default gateway 192.168.4.1).

To connect from the Internet to a host in the internal network (e.g. 192.168.4.2) define a port forwarding on the esp, e.g.
portmap add TCP 80 192.168.4.2 80
and connect to the port 80 of the ESP.

**Comment by ram1505** [comment]
Ok, I don't know what happened, but it is working now. Previously I was trying to access by typing the host name like raspberrypi.local and I couldn't connect. Now I type the IP address of the AP and it works perfectly. Thanks for the detailed instructions.

**Comment by ram1505** [comment]
I guess this will be the last on. I'm using the monitor mode with wireshark. Previously, I used Promiscious mode to capture probe request. When I try nc 172.xxx.xxx.xxx 8888 | sudo wireshark -k -S -i - the wireshark app launches and I only see TCP traffic. When I try to filter using wlan.fc.type_subtype == 0x04, I see nothing. I did try to enable and disable my mobile phone wifi when I did this test to capture a probe. It didn't appear. I then tried http.user_agent == "iPhone" to see ig I can see my iPhone, it too didn't show any result, What am I doing wrongly?

**Comment by martin-ger** [comment]
Nothing wrong: you are looking for IEEE802.11 frames (wlan.fc.type_subtype "Probe Request").
These frames are only visible, when you are physically monitoring the wifi. Can be done with the ESP, but not while in stationAP mode. With the monitoring feature of the repeater you can observe the data frames that are going through the AP including ARP/IP/TCP/UDP, but not physical IEEE802.11 frames. Sorry about that - not possible at this level...
However, the advantage of this monitoring is, that you see decoded frames, not just WPA encoded stuff.

**Comment by ram1505** [comment]
Hi,
I was fiddling around the repeater for a while and I realized that, each time a device connects/ disconnects from the repeater, ESP prints the device's MAC address join, device MAC address leave. Is there any way that I can send this info via MQTT?

**Comment by martin-ger** [comment]
Definitely possible. It would need to integrate e.g. this project https://github.com/tuanpmt/esp_mqtt . The repeater itself can run any TCP/IP application independantly of its repeating (routing) functionality.  Publishing should be done in the WiFi callbacks.

However, nothing I would like to add in the mainline development as it is pretty special feature.

**Comment by ram1505** [comment]
Is there any .ino files which I can play around with and see if I can add it?

**Comment by martin-ger** [comment]
Sorry, no .ino as it is not a Arduino project but based on the native C SDK (esp-open_sdk). 

Maybe I find some time to set up a fork - This functionality might be even interesting for smart home, as it indicates that a certain user has probably entered the covered area (e.g. a home)...

What about this MAC-scanner alone? Would it be of interest to have a scanner, that publishes MQTT events as soon as an new (or a certain well-known) MAC enteres the scene? (without router?) Could probably easily be done as a sketch.

**Comment by ram1505** [comment]
That's precisely the use case I have. I've been trying out a few PCAP tools available for esp. but all of them have the same result as to show the raw output on screen. My programming skills are not that fantastic and I'm banging my head to try and find a suitable method where I can listen to probe request via ESP and send it over MQTT to a server for further processing. A typical tool like wireshark allows one to liste. To probe requests on networks. However, your script does it nicely. It prints the MAC of someone when connected and again when they leave. I'm not concerned about specific MAC address as my primary use case is to find occupancy in a big area like office or a lab. Any help could be much much appreciated.

**Comment by ram1505** [comment]
The router option is not mandatory as I can use the router and the scanner in conjunction to achieve the result.
