### ISSUE TITLE
How many staions on a esp_wifi_repeater can connected?

### ISSUE THREAD

**Issue by TridentTD** [martin-ger/esp_wifi_repeater#170]
Can more than 4 stations?

**Comment by martin-ger** [comment]
Up to 8 should work.

Am 23. März 2018 4:18:05 nachm. schrieb TridentTD <notifications@github.com>:
Can more than 4 stations?

**Comment by TridentTD** [comment]
As I known before up to 8, but I have just found on the last 「 ESP8266 NonOS SDK API Reference 」 page 135/157 about「 struct softap_config  」 , it appears some information that 

  uint_8 max_connection;   // default 4, max 4

If up  to 8 , it's look good for a esp_wifi_repeater.

**Comment by martin-ger** [comment]
Mem is an issue, but the max_connection parameter accepts up to 8 (9 is not accepted) and I have seen more than 4 working.

**Comment by TridentTD** [comment]
Thank you.
