### ISSUE TITLE
Creation of MAGIC_NUMBER config.h

### ISSUE THREAD

**Issue by wellingtons** [martin-ger/esp_wifi_repeater#171]
Hi And thanks for creating this project.  I see a define for MAGIC_NUMBER in config.h but am unsure how it is created.  I can see it in flash, offset by 0xC from 0x0 and notice it changing from version to version in your project.  Is it a random number created for version differences or a checksum?  Just curious.  Thanks.

**Comment by martin-ger** [comment]
It is just a "random" number that is written as first value of the config struct to make sure that there is a valid set of initialized parameters instead of just some values left from previous flashed programs.
