### ISSUE TITLE
can't connect to ssid with space character

### ISSUE THREAD

**Issue by parsamrz** [martin-ger/esp_wifi_repeater#175]
hi i have problem connecting to ssid's that have space in their ssid names for Ex "mrz ssid" please help me Thanks.

**Comment by HowToMeetLadies** [comment]
Hello. He who seeks shall find: There are 6 issues about that topic already. See #154, #132, #108, #85, #75 or #48... 😉

Console: Spaces need to be escaped, so prepend a backslash. Web: Use %20 instead of space. 

@martin-ger: Vielleicht mal ganz oben und besser noch in fett+rot in die README nehmen? 😄

**Comment by martin-ger** [comment]
Use %20 instead of space.

Am 31. März 2018 6:52:35 nachm. schrieb parsamrz <notifications@github.com>:
hi i have problem connecting to ssid's that have space in their ssid names 
for Ex "mrz ssid" please help me Thanks.

**Comment by xmagickx** [comment]
Sorry for commenting. I've read all the issues... I've a unique problem... My AP contains an "APOSTROPHE"... Please suggest a suggestion for this...

 
Shyam's WiFi


How to connect to this by esp8266 wifi repeater module? What characters to replace in place of APOSTROPHE? Even after using \ in place of space it shows + when the name of ssid is given

**Comment by 672Asimk** [comment]
i did use "Air\ Ap" in cli . it save sucessfully save the ssid but cannot connect with "Air Ap" ssid. in arduino serial moniter its only show "Air" not "Air Ap".

**Comment by martin-ger** [comment]
Strange, should work...
Try %20 instead of space.

**Comment by junaidpmr** [comment]
ssid : wifi
Password: 1234567
"192.168.4.1/?ssid=wifi&password=1234567"

Above ssid and password is connected
Problem is ssid: wifi ap
password: 1234567
"192.168.4.1/?ssid=wifi+ap&password=1234567"
Not connected
"192.168.4.1/?ssid=wifi%20&password=1234567"
Not connected
How to connect ssid with space character

**Comment by fuzunspm** [comment]
did you find any solution?

**Comment by martin-ger** [comment]
Please read the Readme.
