### ISSUE TITLE
user/user_main.c:19:26: fatal error: netif/espenc.h: No such file or directory

### ISSUE THREAD

**Issue by torntrousers** [martin-ger/esp_wifi_repeater#181]
I can't get this to build sorry. Have tried to follow the instructions for a Mac, pfalcon/esp-open-sdk built ok, but esp_wifi_repeater make fails right away with fatal error: netif/espenc.h: No such file or directory.

What could I be doing wrong?

**Comment by martin-ger** [comment]
Sorry, my fault. Added that lately and the include path only works in my environment. Should be: "#include lwip/netif/espenc.h". Fixed that in the repo - Thanks!

**Comment by felixwe710** [comment]
Hey, das Problem ist wieder da - oder noch immer. Ich habe versucht den ENC28J60 Support über die user_config.h zu aktivieren und bekomme beim make-Befehl dann folgendes:

`CC user/user_main.c
user/user_main.c:25:26: fatal error: netif/espenc.h: No such file or directory
 #include "netif/espenc.h"
                          ^
compilation terminated.
Makefile:172: die Regel für Ziel „build/user/user_main.o“ scheiterte
make: *** [build/user/user_main.o] Fehler 1
`

Leider kann ich die zuständige Datei auch nicht bearbeiten...

LG Felix

**Comment by martin-ger** [comment]
Bitte mal hiermit versuchen:

https://github.com/martin-ger/esp-open-lwip/blob/enc_polling/include/netif/espenc.h

**Comment by felixwe710** [comment]
> Bitte mal hiermit versuchen:
> 
> https://github.com/martin-ger/esp-open-lwip/blob/enc_polling/include/netif/espenc.h

Hey, habe ich grade gemacht...bringt nichts - der Fehler wird ja auch von der user_main.c geworfen und nicht von der espenc.h.

Ein Kopieren und Verschieben der Dateien in den include Ordner geht auch nicht, da es dann in beiden fällen wiederum Fehler wirft... wenn ich den Ethernet Adapter abschalte läuft alles brav durch...

**Comment by felixwe710** [comment]
Ich hab es jetzt geschafft - die user_mail.c wurde mir erst kryptisch dargestellt - jetzt konnte ich es aber lesen und entsprechend das lwip ins #include setzen... nun gibts aber leider wieder einen Fehler - auch wenn ich die espenc.h durch die von Dir verlinkte anpasse.

Hier der Code:
`AR build/app_app.a
/home/felix/nat_repeater_/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: build/app.out section `.text' will not fit in region `iram1_0_seg'
collect2: error: ld returned 1 exit status
Makefile:132: die Regel für Ziel „firmware/0x02000.bin“ scheiterte
make: *** [firmware/0x02000.bin] Fehler 1
`

Den Fehler habe ich auch bekommen, als ich die espenc.h ins include Verzeichnis Kopiert habe (logisch, wenn er es dann findet..).

Im Internet habe ich bereits nach Lösungen dazu gesucht - aber nichts gefunden. Klappt es denn bei Dir lokal wenn du den Adapter hinzufügst? Wenn ja, dann muss der Fehler ja trotzdem irgendwo bei mir liegen...

LG Felix
