### ISSUE TITLE
Unable to unlock

### ISSUE THREAD

**Issue by qq1198** [martin-ger/esp_wifi_repeater#184]
STA Wifi Open Network Not Password Config Unable to unlock

**Comment by martin-ger** [comment]
"...Now the config cannot be changed anymore without first unlocking it with the uplink WiFi network's password (**define one even if the network is open**)."

**Comment by qq1198** [comment]
WiFi Password is Open.
But 192.168.4.1 Config Lock Empty password Unable to unlock.

**Comment by qq1198** [comment]
@martin-ger Need re flash?
