### ISSUE TITLE
Vdd is wrong

### ISSUE THREAD

**Issue by destroyedlolo** [martin-ger/esp_wifi_repeater#187]
Hello,

I upgraded my ESP-01 to latest Version V1.8.1 (build: Fri Apr 20 09:50:20 2018)
But published Vdd is now wrong.

Topic: xxxx/Vdd, message: '63996'

Best regards,

Laurent

**Comment by destroyedlolo** [comment]
I noticed also this version output garbage for help command :

CMD>help
show [config|stats|route|dhcp|acl|mqtt]
set [ssid|password|auto_connect|ap_ssid|ap_password|ap_on|ap_open|nat] <val>
set [ap_mac|sta_mac|ssid_hidden|sta_hostname|max_clients] <val>
set [network|dns|ip|netmask|gw] <val>
set [eth_enable|eth_ip|eth_netmask|eth_gw|eth_mac] <val>
route clear|route add <network> <gw>|route delete <network>
interface <int> [up|down]
portmap [add|remove] [TCP|UDP] <ext_port> <int_addr> <int_port>
show acl|acl [from_sta|to_sta|from_ap|to_ap] [IP|TCP|UDP] <src_addr> [<src_port>] <dest_addr> [<dest_port>] [allow|deny|allow_monitor|deny_monitor]
acl [from_sta|to_sta|from_ap|to_ap] clear
set [daily_limit|timezone] <val>
ping <ip_addr>
monitor [on|off] <portnumber>
set [upstream_kbps|downstream_kbps] <val>
set [automesh|am_threshold|am_scan_time|am_sleep_time] <val>
set [speed|status_led|hw_reset|config_port|config_access|web_port] <val>
save [config|dhcp]
connect|disconnect|reset [factory]|lock|unlock <password>|quit
set [client_watchdog|ap_watchdog] <val>
scan
set phy_mode [1|2|3]
sleep <secs>
set [vmin|vmin_slee��Ĕ$@���yA�$@za����R��?�p�|\$@b��?d��?e��?c��?^��?

Bye

**Comment by martin-ger** [comment]
If the supply voltage in the "show stats" command shows a wrong (high) value, the ADC isn't configured correctly. Re-initialize the ESP with the "esp_init_data_default_v08_vdd33.bin" as described in the Readme.md.

I will look into the help command - string is too long...

**Comment by martin-ger** [comment]
Latest upload should fix it.
