### ISSUE TITLE
Net name is not showing as before

### ISSUE THREAD

**Issue by imayoda** [martin-ger/esp_wifi_repeater#189]
Minor bug for sure.
If I remember correctly, in fritz!box wireless stations list it was showing a real name, not ESP-xxxx ..
Just for your info.. thanks :)

**Comment by martin-ger** [comment]
Don't think, there was another name before. But since a few weeks you can change this name on the CLI with:
"set sta_hostname name"

**Comment by imayoda** [comment]
urgh, shame on me :blush:
