### ISSUE TITLE
connected, no internet access

### ISSUE THREAD

**Issue by zhengxxcc** [martin-ger/esp_wifi_repeater#193]
Hi, 

In my testing, I tried to flash with the 2 bin files and also 3 bin files. and I did configuration on 192.168.4.1, but saw the message  "connected (no internet access) on my mobile. 
after connect to the MyAP, I can not access web site on internet. Do I have to do other configuration on STA router or mobile?  Thanks!

-Wei

**Comment by martin-ger** [comment]
For first config, this is fine. Now you have to configure the AP you want to connect to. See also: https://github.com/martin-ger/esp_wifi_repeater#first-boot

**Comment by zhengxxcc** [comment]
Thanks Martin! It works now, my mistake
