### ISSUE TITLE
WIFI Repeater

### ISSUE THREAD

**Issue by sorriso93** [martin-ger/esp_wifi_repeater#197]
I read the documentation and also the issues but I must admit I didn't find or understood a simple answer to my question.
Is it possible to use esp_wifi_repeater as a simple repeater, i.e. no NAT but a simple extender if current wifi network with no different ip subnet.
thanks

**Comment by martin-ger** [comment]
Sorry, no you cannot. Ir's actually a Router only.

Am 22. Mai 2018 12:50:01 vorm. schrieb sorriso93 <notifications@github.com>:
