### ISSUE TITLE
not working on Esp 12F module

### ISSUE THREAD

**Issue by Sonanash** [martin-ger/esp_wifi_repeater#201]
I have tried on NODECU 12E, its work like charm, but when i tried it on esp 12f , only getting a garbage values on serial out at 115200 BAUD. Tried downlaod esp_init_data_default bin file at address 0x7fc000 and 0xfc000. but did not worked. 
Please help.

**Comment by martin-ger** [comment]
On a 4MB module the init_data has to go to 0x3fc000.

**Comment by Sonanash** [comment]
Tried with DIO mode and its works like charm for both esp12f and webmos D1.
Thanks a lot.
