### ISSUE TITLE
Extremely low speed with one client connected.

### ISSUE THREAD

**Issue by yossef12adar** [martin-ger/esp_wifi_repeater#203]
I just flashed the default bin files to my ESP8266 chip, and I set some basic settings through the interface at 192.168.4.1...
the connection work but its extremely slow! nearly two or three minutes to enter google.
here are some speedtest results:
wifi repeater bought at store:
http://www.speedtest.net/result/7439765755
ESP8266:
http://www.speedtest.net/result/7439774766
I would be glad for some help,
thanks in advance...

**Comment by marek26340** [comment]
Have you tried a different browser?

**Comment by martin-ger** [comment]
Try to start with a short range. Also try to "ping" the device.

There is no known general throughput problem.

**Comment by yossef12adar** [comment]
I tried different browsers and different devices. the repeater is located at a good place and I have 4 bars on the wifi logo...

**Comment by marek26340** [comment]
How wide is the bandwidth of your WiFi? I was experimenting one day.. I tried to set BW to 20MHz and the speed of the WiFi repeater increased a bit...

**Comment by yossef12adar** [comment]
I relocated the repeater and I managed to achieve 1.92mbits/s (http://www.speedtest.net/result/7441341356)
is that the speed I should expect? anyone succeed to get more speed?

**Comment by martin-ger** [comment]
This is at least in the range of what one could expect: many people have reported 4 Mbps and more. Maybe it is an antenna issue. Obviously it is not a performance problem of the ESP...

**Comment by yossef12adar** [comment]
OK, thank you all for your responses, closing this issue...
