### ISSUE TITLE
Spaces in password is not supported

### ISSUE THREAD

**Issue by ViliusSutkus** [martin-ger/esp_wifi_repeater#206]
So I've tried to connect to SSID that has some special characters in the password. One of those characters is space. Didn't go very well.

If I try to enter the config through web config, it replaces spaces with plus + signs.
If I use serial line config, password is cut off from the first space.

**Comment by martin-ger** [comment]
If you want to enter non-ASCII or special characters in the web interface 
you have to use HTTP-style hex encoding like "My%20AccessPoint". This will 
result in a string "My AccessPoint". With this hex encoding you can enter 
any byte value you like, except for 0 (for C-internal reasons).

Am 11. Juli 2018 23:38:36 schrieb Vilius Sutkus <notifications@github.com>:

**Comment by ViliusSutkus** [comment]
Thanks Martin.
