### ISSUE TITLE
Connecting FritzBox

### ISSUE THREAD

**Issue by wchulze** [martin-ger/esp_wifi_repeater#213]
Hallo Martin,

ich möchte den NAT Repeater als " Netzwerk Verlängerung" für die Sonoff S20/Basic mit Tasmota einsetzen.  Als Betriebssystem ist Windows 10 im Einsatz. Der Router im Heimnetz ist eine Fritz-Box 7390.

Das Programmieren des ESP-01 ging dank Ihrer Beschreibung reibungslos.
Ich habe den STA und den AP mit der SSID und dem Passwort der Fritz-Box ins Netzwerk gebracht ( AP und STA identisch ). Das sind die Werte von der Konsole: 

CMD>show stats
System uptime: 0:20:15
Local time: Mon Jul 23 14:09:42 2018
115 KiB in (813 packets)
1239 KiB out (1040 packets)
Power supply: 3.349 V
Phy mode: n
Free mem: 19576
STA IP: 192.168.178.52/24 GW: 192.168.178.1
STA RSSI: -55
2 Stations connected to SoftAP
Station: 00:1f:1f:b4:7e:e6 - 192.168.4.2
Station: 5c:cf:7f:72:36:20 - 192.168.4.3

CMD>show route
Routing table:
Network              Dest
192.168.4.0/24       ew1
192.168.178.0/24     ew0
127.0.0.0/8          lo0
default              192.168.178.1

Die URL 192.168.178.1 gehört meiner Fritz-Box.

192.168.4.2 ist ein Laptop verbunden mit dem Repeater.
192.168.4.3 ist ein Sonoff mit Tasmota.

Auf der Repeaterseite vom Laptop aus, ist der Sonoff mittels „Ping 192.168.4.3“ zu erreichen.
Ein „Ping 192.168.4.3“ auf der Fritz.-Box Seite - mein PC in der Fritz-Box eingeloggt -  schlägt fehl.

Nun trenne ich den Sonoff vom Repater und logge ihn in der Fritz-Box ein.
Er bekommt dort die IP 192.168.178.21

Ein „Ping 192.168.178.21“ auf dem PC mit der Fritz-Box und auf dem Laptop mit dem Repeater gelingen sofort ohne Probleme.

Nun zu meinem Problem  oder Frage:

Was mache ich falsch oder kann ich noch tun, um den Sonoff auch vom PC aus auf der Repeater Seite zu erreichen?

Mit freundlichem Gruß

Wolfgang Schulze

**Comment by martin-ger** [comment]
Hallo,

das Problem ist NAT. Um den Sonoff von der Fritzbox-Seite auf der anderen 
Seite zu erreichen, muss ein Port-Forwarding eingerichtet werden. Wie soll 
denn der Sonoff erreicht werden? Mit Http?

Am 23. Juli 2018 20:24:54 schrieb wchulze <notifications@github.com>:

**Comment by wchulze** [comment]
Hallo Martin,
danke für die schnelle Antwort.

Der Sonoff soll über HTTP  und ebenfalls via Amazon Echo ( Belkin WeMo ) erreichbar sein.
Ist das Port-Forwarding  auf der Fritz-Box oder dem Repeater notwendig und wie?

**Comment by martin-ger** [comment]
`portmap add TCP 80 192.168.4.3 80`
auf dem Repeater, dann kann man mit HTTP den Sonoff unter der Adresse des Repeaters erreichen. Um sicher zu stellen, dass der Sonoff immer die gleiche IP via DHCP erhält, sollte man `save dhcp` machen, wenn er eingeloggt ist.

Verbindungen von innen nach aussen - also z.B. eine MQTT-Verbindung vom Sonoff auf einen Broker aussen - klappen auch so dynamisch.

Ich weiss allerdings nicht, welches protokoll der Echo nutzt.
