### ISSUE TITLE
SSID with Space Chacrater Fail

### ISSUE THREAD

**Issue by TienHuyIoT** [martin-ger/esp_wifi_repeater#214]
Hi Martin,
If Wifi Name (SSID) has space character, Esp8266 can't connect to it. Because Space character has replaced with Plus character (+).

**Comment by martin-ger** [comment]
Relpace Spacey by %20 as describen in the Readme.md.

Am 27. Juli 2018 10:21:53 schrieb TienHuyIoT <notifications@github.com>:

**Comment by TienHuyIoT** [comment]
Thanks Martin!

**Comment by xmagickx** [comment]
Sorry to comment again... In the web interface of ESP Wifi repeater the AP I want to connect to is named as "Shyam's Wifi"... Even after trying with %27 for APOSTROPHE & %20 OR \ for space it's not helping & I'm not being able to connect to the AP to extend my range... Please help me out...

**Comment by martin-ger** [comment]
You might try via telnet.

Am 31. August 2019 14:50:53 schrieb xmagickx <notifications@github.com>:
