### ISSUE TITLE
Open access to enable monitor, even after lock + save

### ISSUE THREAD

**Issue by jaggzh** [martin-ger/esp_wifi_repeater#215]
How is one to save the device in a locked state so it's locked after resetting?

I locked, with a lock password, but then had to unlock in order to save (and then reset)..
After the reset, I could still access port 7777 and make configuration changes.

**Comment by martin-ger** [comment]
Just enter "lock" or "lock password". This already saves the current config.

Try reset and you will be able to connect to 7777 but won't be able to do any changes.

If you want to disable port 7777 completely: "set config_port 0" and "save" (serial console still works and is not locked).

With "set config_access [0|1|2|3]" you can also control the networks that allow config access for console and web (0: no access, 1: only internal, 2: only external, 3: both (default))
