### ISSUE TITLE
mqtt LWT???

### ISSUE THREAD

**Issue by hwarang098tkd** [martin-ger/esp_wifi_repeater#217]
Is there any topic for the mqtt last will and testament???
Online and offline
thanks in advance

**Comment by martin-ger** [comment]
Good idea! Added LWT and status report the repeater publishes:
_prefix_path_/status: A retained topic either "online" (as soon as the repeater connects) or "offline" (after connection loss as LWT)

**Comment by hwarang098tkd** [comment]
ok. Is there any way to save my configuration before flash the module again in order to update?

**Comment by martin-ger** [comment]
No need to - as long as the config data and magic-number do not change, the current config will presist a re-flash of the firmware.

BTW: just updated the LWT implementation

**Comment by hwarang098tkd** [comment]
thnx
