### ISSUE TITLE
Web interface to control the repeater

### ISSUE THREAD

**Issue by nisc3** [martin-ger/esp_wifi_repeater#22]
Is it possible to build a web interface to add/remove networks, to change the name and password of the extended networks etc.?

**Comment by martin-ger** [comment]
As I said in another issue: certainly possible, even desirable. However, I am not a Web/GUI person: libesphttpd should be a good option to implement a Web-GUI. Adding the server structure shouldn't be a big deal. For me a problem would be the page design and the JS-part. I am really not into that. Anybody willing and able to support this?

**Comment by RibeiroSantos** [comment]
I will try to design some pages using json and ajax (but busy until next week)

**Comment by martin-ger** [comment]
Would be great. I could definitely add the server structure.
