### ISSUE TITLE
Can I extend a network with 802.1x authentication?

### ISSUE THREAD

**Issue by alessandro308** [martin-ger/esp_wifi_repeater#221]
Reading the docs, seems that the only parameters that I can pass are user and password for connecting to some access point. Can I extend (so connect to) a network that uses 802.1x authentication?

**Comment by martin-ger** [comment]
Was trying to integrate this functionality into this project - however this is difficult, as WPA2 enterprise requires so much free heap during authentication that there is hardly any mem left for anything else. So I decided to leave that in a separate project. Have a look at: https://github.com/martin-ger/esp_peap_psk
