### ISSUE TITLE
No booting with ENC28J60 

### ISSUE THREAD

**Issue by vfperri88** [martin-ger/esp_wifi_repeater#222]
Hi, could anyone make it boot whith the ENC28J60 connected? I follow the instructions to the connection but my ESP don't boot any more unless I disconnected the GPIO15 and connected it to GND. My connection schema is the following and I'm using the transistor for decoupling GPIO15.

NodeMCU/Wemos  ESP8266      ENC28J60

        D6     GPIO12 <---> MISO
        D7     GPIO13 <---> MOSI
        D5     GPIO14 <---> SCLK
        D8     GPIO15 <---> CS
        D1     GPIO5  <---> INT
               Q3/V33 <---> 3.3V
               GND    <---> GND

Thanks!

Victor

**Comment by martin-ger** [comment]
If you try to pull GPIO15 low with the decoupling transistor directly at the pin - let's say with additional 3,3kOhm?

**Comment by vfperri88** [comment]
> If you try to pull GPIO15 low with the decoupling transistor directly at the pin - let's say with additional 3,3kOhm?

Thank you very much @martin-ger. I could solve the problem booting putting an additional pull down resistor.
