### ISSUE TITLE
restt to default

### ISSUE THREAD

**Issue by blucmal** [martin-ger/esp_wifi_repeater#223]
Sorry I am a noob how do I do this 

> HW Factory Reset
If you pull low GPIO 4 for more than 3 seconds, the repeater will do a factory reset and restart with default config. With "set hw_reset GPIOno" the GPIO pin can be changed (any value > 16, e.g. "set hw_reset 255" will disable the hw factory reset feature).

Will not accept my password even though I only typed it 3 secs before I tried logging in. Cant reach it via telenet or serial as it does not show up in device manager....

**Comment by martin-ger** [comment]
You can always reach the console via the serial port (115200 baud). If you see the "CMD>" prompt, you can enter "reset factory" and you should get a vanilla config.
