### ISSUE TITLE
SOS! SOS! emergency!emergency! Why can‘t i modify the ap_mac???

### ISSUE THREAD

**Issue by unix1024** [martin-ger/esp_wifi_repeater#234]
I use the command "set ap_mac xx:xx:xx:xx:xx:xx" to modify the esp8266's mac.   And the tool display i have modify the mac.   
![image](https://user-images.githubusercontent.com/12093421/46882238-88bca400-ce80-11e8-8f8e-28c36cda98a2.png)

But!!!But!!!  when i upload the program to esp8266, it still display the old mac!!!
![image](https://user-images.githubusercontent.com/12093421/46882303-b86bac00-ce80-11e8-9472-0eaac2a41fe6.png)

moreover!!   I use my computer to connect the esp8266, and catch the packet ,   the destination mac still the old mac 
![image](https://user-images.githubusercontent.com/12093421/46882406-2ca64f80-ce81-11e8-9d5b-a0128f28f706.png)

SOS! Help!

**Comment by unix1024** [comment]
please help me , thank you ! God bless you , Dear.

My we-chat: 17801141216
My phone : 17801141216
My e-mail: unix1024@163.coom

**Comment by martin-ger** [comment]
Change is only temporary for the wifi_repeater. Other programs will still read the original MAC from ROM.

**Comment by unix1024** [comment]
Oh，thank you very much for your help. I have found the question. I don’t execute the command to save the config. Oh，my god. I am so idiot！
