### ISSUE TITLE
How to set Wifi channel 8266 different from the channel of the main router?

### ISSUE THREAD

**Issue by abf1** [martin-ger/esp_wifi_repeater#238]
How to set Wifi channel in Esp8266 different from the channel of the main router?
In my case, I have the same Esp8266 channel as the main router channel. And I would like for an example the channel of the router 1, and the channel 8266 - 12. How can this be done?

**Comment by martin-ger** [comment]
Impossible, as the ESP in STATIONAP mode must run both interfaces on the same channel - obvious, as the ESP has just one transceiver (and thus one channel at a time) and the two interfaces cannot run reliably in time-slotted mode.

**Comment by PepeTux** [comment]
Its possible, but when you change your ESP8266 channel you will be disconnected from your WiFi Router.
(I know this is an old post but maybe its useful for somebody).

this is the code for the ESP8266:
`#include <ESP8266WiFi.h>
  Serial.printf("\r\nWifi Channel: %d\n", WiFi.channel() );
  wifi_set_channel(9);
  Serial.printf("\r\nWifi Channel: %d\n", WiFi.channel() );
`

and this is the code for the ESP32:
`void Change_Wifi_Channel(byte mChann)
{
  uint8_t channel_curr = WiFi.channel();

  // Change Channel manually.
  esp_wifi_set_promiscuous(true);
  esp_wifi_set_channel(mChann, WIFI_SECOND_CHAN_NONE);
  esp_wifi_set_promiscuous(false);

  ESP_LOGI(TAG_SCH, "\r\nChanged Channel from %d to %d.\n", channel_curr, mChann);    
}`

Saludos
JL
