### ISSUE TITLE
[Space] in Base station password doesnt work 

### ISSUE THREAD

**Issue by yeshu007** [martin-ger/esp_wifi_repeater#241]

**Comment by martin-ger** [comment]
If you want to enter non-ASCII or special characters you can use HTTP-style hex encoding (e.g. "My%20AccessPoint") or, only on the CLI, as shortcut C-style quotes with backslash (e.g. "My\ AccessPoint"). Both methods will result in a string "My AccessPoint".

**Comment by yeshu007** [comment]
Thank you my problem is solved by using blackslash( \ ) in password.
