### ISSUE TITLE
wifi_set_macaddr can only be called in user_init

### ISSUE THREAD

**Issue by daffysub** [martin-ger/esp_wifi_repeater#247]
I seen an unexpected behavior with this project and discover that the MAC address is not only set in the user_init.
I have seen in the SDK documentation that we can only be called in user_init.

Is it a voluntary choice or an oversight?

To finish, I want thank you for this excellent project.

**Comment by martin-ger** [comment]
MAC change has to be done during init, that's right.

When the new MAC is set from the command line of the repeater it is not actually applied. Store it with "save" and "reset" the ESP. Then it will be initialized with the new MAC.

**Comment by daffysub** [comment]
Ah yes! thank you for your quick reply
