### ISSUE TITLE
The Standalone branch

### ISSUE THREAD

**Issue by Clancys74** [martin-ger/esp_wifi_repeater#248]
Hello,

First, an excellent and remarkable job has been done here. I am personally a complete noob on everything related to network so i am kind of amazed.

I want to use this function to relay the WIFI through some ESPs, however as i don't need and want the external console part and everything related to it, i thought i would use the standalone version of your build. However, this version looks really old and untouched for a long period of time.

Is it compatible with the esp-open-sdk v2.2.0 ?
If yes, can i use only the "repeater" part without anything else easily? 

In fact, i am using the network part in the esp-open-sdk v2.2.0 for Wifi connection, UDP connection with message broadcast, TCP connection to a database in HTTPS and TCP connection to a phone in HTTP. All of this through the Wifi and the espconn functions.

If i use your build, will i have to change all the logic and/or the function's name in the network part of my program? Or will i be directly good to go ?

Best regards,
Clancys74.

**Comment by martin-ger** [comment]
In fact, there is no real standalone version of this.

Option 1 would be to use it as is and simply disable the console with:
```
set config_port  0
set web_port 0
save
```
This has the advantage, that you can still configure it dynamically before usage. You can also disable most features (MQTT, ACLs etc.) staically in user_config.h.

Option 2 would be just to use https://github.com/martin-ger/esp-open-lwip and make your own esp-open-sdk project. Just use this call from lwip_napt.h after init for the AP interface:

```
/**
 * Enable/Disable NAPT for a specified interface.
 *
 * @param addr ip address of the interface
 * @param enable non-zero to enable NAPT, or 0 to disable.
 */
void ICACHE_FLASH_ATTR
ip_napt_enable(u32_t addr, int enable);
```
It will add the routing and NAPT feature to your program.
