### ISSUE TITLE
NAT table timeout should be configurable

### ISSUE THREAD

**Issue by jcea** [martin-ger/esp_wifi_repeater#253]
Currently, UDP NAT table timeout is only 2 seconds. Quite low, but probably OK for DNS. When dealing with VPN traffic over UDP, 2 seconds NAT table timeout is not enough. Not at all.

I understand the need to keep the NAT timeout low because ESP8266 memory is quite limited, but would be nice if that detail could be configured in the CLI. I am currently using a modified version of this software with a UDP NAT timeout of 65 seconds. No issues so far, although my network is quite small (maybe 3-5 devices).

I would love to be able to change the NAT timeout via CLI, even if that requires a reboot.

Thanks.

**Comment by martin-ger** [comment]
Good point - will add this later today...

**Comment by martin-ger** [comment]
See latest version...
