### ISSUE TITLE
ENC28J60 ld returned error

### ISSUE THREAD

**Issue by tar-dig** [martin-ger/esp_wifi_repeater#255]
Did steps to build as described, executed make with no errors.  Then changed user_config.h so HAVE_ENC28J60 set to 1,  changed to INCLUDE  to: EXTRA_INCDIR    = include $(BUILD_AREA)/esp_wifi_repeater/include/lwip so espenc.h could be accessed. Running make now gives error:
esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: build/app.out section `.text' will not fit in region `iram1_0_seg'
collect2: error: ld returned 1 exit status
Makefile:134: recipe for target 'firmware/0x02000.bin' failed
make: *** [firmware/0x02000.bin] Error 1

Must be my problem since others have used enc28J60 without problem.  I have searched without success, thus I am asking for some help/insight.

Thanks for your help.

**Comment by martin-ger** [comment]
Please change the Makefile:
```
# compiler flags using during compilation of source files
CFLAGS		= -Os -ffunction-sections -fdata-sections -g -Wpointer-arith -Wundef -Werror -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals  -D__ets__ -DICACHE_FLASH -DLWIP_OPEN_SRC -DUSE_OPTIMIZE_PRINTF

# linker flags used to generate the main object file
LDFLAGS		= -ffunction-sections -fdata-sections -Wl,-gc-sections -nostdlib -Wl,--no-check-sections -u call_user_start -Wl,-static -L.
```

Will test this a little bit further and include it in the main tree later...

**Comment by tar-dig** [comment]
Thanks for you rapid reply.  Made the changes and it loaded without errors.  Greatly appreciate your help.


----- Original Message -----
