### ISSUE TITLE
192.168.4.1

### ISSUE THREAD

**Issue by MrFanLee** [martin-ger/esp_wifi_repeater#256]

**Comment by MrFanLee** [comment]
when i use my phone to connect the esp8266 router, i can't open this address 192.168.4.1 in browser. i don't know why. My phone ip is 192.186.4.2. ESP8266 IS 192.168.4.1

**Comment by martin-ger** [comment]
At least my new Andriod phone waits with the connection until I confirm, that I really want to connect to network, that has (not yet) internet connectivity. Maybe this is similar on iPhones? Can you connect using a PC?
