### ISSUE TITLE
flashing firmware on windows

### ISSUE THREAD

**Issue by herrxyz** [martin-ger/esp_wifi_repeater#260]
Hey Martin,

I tried the install-steps, but it does not work. Serials prints out just gibberish stuff, LED on my wemos d1 mini just blinks once for less than 0.1s (same for esp8266-01)
haven't used the esp-tool you mentioned before, so there may be something wrong in my settings
tried it with and without esp_init_data_default_v08_vdd33.bin, which was mentioned somewhere in Issues
![esp8266_tool](https://user-images.githubusercontent.com/7574166/50982155-d1760e80-14fc-11e9-9b63-513f6aa0b8a1.png)
any idea what to try next? dowloaded firmware directly from firmware-folder from repo

Kind regards

**Comment by martin-ger** [comment]
Did you check the checksums? Sometimes there are problems with CR-LF when downloading it with Windows. Try to download the repo as zip and extract the binaries from there.

**Comment by zoomx** [comment]
Did you try the QIO mode first?

**Comment by herrxyz** [comment]
I already anwered, but it seems to be gone... really strange
so, working solution was, as suggested by @martin-ger, to download the whole repo as zip instead of directly download it ("save link as"). As linebreaks are different in windows and linux, as far as I understand this was the reason why it didn't work in the first time
