### ISSUE TITLE
 how to clear wifi settings?

### ISSUE THREAD

**Issue by kitty801** [martin-ger/esp_wifi_repeater#269]
Please explain, how to clear wifi settings, when my ESP8266 works in Automesh mode.
I've tried to connect GPIO0 to ground for more than 3 seconds. But when I need to do it? During booting or after connect?

And also I need to send set **hw_reset GPIO0** and **save** commands via console after flash?

Nothing helps.
I can do it only via console, but I'd like to do it other way (when I will plug my ESP to a device).

**Comment by martin-ger** [comment]
During config enter on the terminal:
```
set hw_reset **GPIOno**
save
```
This selects a GPIO pin for a hardware factory reset (>16 disabled, default). Then a three seconds low on this pin will cause a factory reset (only hw_reset settings will be preserved).

**Comment by kitty801** [comment]
I have a little bit problem with clearing wifi settings
After connect GPIO0 to ground for few secunds, my ESP do a factory reset. But I can't do it again. I have to send **set hw_reset GPIO0** command again.
I think my setting which pin is uses to do factory restet is lost now.

**Comment by kitty801** [comment]
Ok, now I can clear wifi settings by connect GPIO0 to ground for few secunds.
Or I can do it from telnet app from my phone (if my ESP8266 works as AP mode I can connect with it).
But how to do it, if my ESP8266 works in Automesh mode?

**Comment by avinash1598** [comment]
> Ok, now I can clear wifi settings by connect GPIO0 to ground for few secunds.
> Or I can do it from telnet app from my phone (if my ESP8266 works as AP mode I can connect with it).
> But how to do it, if my ESP8266 works in Automesh mode?

erase flash using arduino ide and startover from the first step.
