### ISSUE TITLE
How to change acces point name?

### ISSUE THREAD

**Issue by kitty801** [martin-ger/esp_wifi_repeater#272]
How to change acces point name?
I've tried to change WIFI_AP_SSID "MyAP" entry in user\user_config.h and then recompile project, but acces point is always MyAP.

**Comment by martin-ger** [comment]
Try a "reset factory" on an ESP that had the original version installed before.

**Comment by kitty801** [comment]
It doesn't helps.
After factory reset and flash my recompiled bin , acces point is MyAP 
even though I entered a different name in the **user\user_config.h** file.
Do I need to recompile some other files in esp-open-sdk dir?

**Comment by kitty801** [comment]
Also I'v tried to change some texts in user\web.h file and I don't see my changes too.

**Comment by robnewton** [comment]
I ran into that issue and had to erase then reflash before it was fixed. Didn't look into root cause.

**Comment by kitty801** [comment]
I've found what was problem.
Before every make command, I have to delete **build** dir.

**Comment by martin-ger** [comment]
The ESP saves its last WiFi config in flash in the high memory blocks. It restarts with the latest config. If you either write a new one or erase the complete memory it will be gone.

With the WiFi repeater you can either do a "reset factory" via CLI (same as pulling the pin down) or simply configure a new one and do "save" "reset"

**Comment by kitty801** [comment]
But I don't want to unplug my repeater and plug to computer to send factory reset command.
I'd like to do it wireless.

**Comment by martin-ger** [comment]
You can log into the ESP: with "telnet 7777 192.168.4.1",  on windows use putty. Now you can enter all commands incl. "reset factory".

**Comment by kitty801** [comment]
I'm connected to my network (but my ESP works in mesh mode , so I don't know if connection is via ESP or directly to router).
Then I try to log into the ESP with "telnet 7777 192.168.4.1" (use putty) but I can't connect.
I have to connect via ESP?

**Comment by gordoste** [comment]
He made a typo. Use "telnet 192.168.4.1 7777"
