### ISSUE TITLE
Mac address

### ISSUE THREAD

**Issue by odaiayoob** [martin-ger/esp_wifi_repeater#280]
Hello,

how can I find the real mac address, AP mac and STA mac changing each reboot, but I need fixed and real Mac address for the current ESP device

**Comment by martin-ger** [comment]
MAC addesses should be fix as long as you not configure "random".
"reset factory" should (re-)set it to the fixed HW-defined MAC addresses.

**Comment by odaiayoob** [comment]
Dear martin-ger,

Thank you for the response, can you give me the commands to make it fixed?

**Comment by martin-ger** [comment]
The standard should be fixed.

**Comment by odaiayoob** [comment]
Many Thanks,

The default sta_mac is the fixed IP for Current Hardware
