### ISSUE TITLE
ESP8266 section `.text' will not fit in region `iram1_0_seg'

### ISSUE THREAD

**Issue by fenglaijun** [martin-ger/esp_wifi_repeater#288]
i had disable many features in user_config.h,but it still not work.make error:
section `.text' will not fit in region `iram1_0_seg'

**Comment by gr01d** [comment]
Try this:
Okay, the solution was to copy the libgcc.a file from:

esp-open-sdk/ESP8266_NONOS/lib/

to

esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5

https://www.esp8266.com/viewtopic.php?p=59022

**Comment by fenglaijun** [comment]
i solve this, just add 'ICACHE_FLASH_ATTR' more in code
