### ISSUE TITLE
Max Stations

### ISSUE THREAD

**Issue by capedra** [martin-ger/esp_wifi_repeater#3]
I suggest you to let the user configure the maximum number of stations using telnet and also the option to set the ESP to work at 160 MHz. Would also be great to see it working on Wemos D1 Mini with battery shield. With my tests, I got 10 Mbps on the ESP-01.  Congratulations for this amazing firmware.

**Comment by martin-ger** [comment]
The max nuber of stations is limited by the Espressif libs to 8 anyway. Thus, a function may only further reduce this limit. Would this really be helpful faeture?

Will experiment a little bit with overclocking...

**Comment by capedra** [comment]
Good to hear from you, Martin. According to some users from ESP8266.com, the max number of stations can be changed directly on Espressif libs but I don't know yet what is the outcome if you change it. I think it's helpful for places where there are more than 8 devices around and you don't want to use another repeater. I will try to test your great project using Wemos D1 Mini soon. Thanks!

**Comment by capedra** [comment]
Would be great to configure the desired CPU speed using Telnet. Thanks!

**Comment by martin-ger** [comment]
Try the new version...

 

Von: capedra [mailto:notifications@github.com] 
Gesendet: Freitag, 13. Januar 2017 07:57
An: martin-ger/esp_wifi_repeater
Cc: martin-ger; Comment
Betreff: Re: [martin-ger/esp_wifi_repeater] Max Stations (#3)

 

Would be great to configure the desired CPU speed using Telnet. Thanks!

**Comment by martin-ger** [comment]
Espressif says: limit of maxstations is 8 in the latest SDK: http://bbs.espressif.com/viewtopic.php?t=1894
This corresponds to my tests: setting it to any value greater than 8 in the config will still respond 8 when you read it back. Currently , I don't see a chance to increase this.
