### ISSUE TITLE
esp_uMQTT_broke: MQTT Invalid protocol

### ISSUE THREAD

**Issue by RibeiroSantos** [martin-ger/esp_wifi_repeater#30]
Hi,
When I try use with the MQTT Lens application is gives the message "MQTT: Invalid protocol".
Is just compile, upload, and create a client connection, yes?

**Comment by martin-ger** [comment]
It requires MQTT v3.1.1, this message means that the client probably tried with v3.1.

**Comment by RibeiroSantos** [comment]
Using MQTT Lens, we can select tcp: or ws.

tcp:  "MQTT: Wrong protocoll version" 
ws:   "MQTT: Invalid message    MQTT: Partial message received"

firmware compiled with 
//-#define PROTOCOL_NAMEv31  /*MQTT version 3.1 compatible with Mosquitto v0.15*/
#define PROTOCOL_NAMEv311     /*MQTT version 3.11

**Comment by martin-ger** [comment]
Chrome MQTTLense seems to be v3.1 only. Used mqtt-spy for Java which does both.

Now uploaded a version that understands the v3.1 connect header. Seems to work for me with MQTTLense.

Switch is currently in the file mqtt/include/mqtt_msg.h
