### ISSUE TITLE
Locking device

### ISSUE THREAD

**Issue by lisekxd1234** [martin-ger/esp_wifi_repeater#313]
Hi, 

my name's Jacob. First of all sorry for my bad English. I just discovered new big issue. In my company we need to have very long password. My password has 63 characters. When I set up esp using my password i alawys get my device locked and i don't know what can i do. After setup password I can't get to configuration. Default pass not working... Waiting for your reply! :)

**Comment by martin-ger** [comment]
Latest version should fix this problem. Thanks for your report.
