### ISSUE TITLE
Unable to Change Phy_mode

### ISSUE THREAD

**Issue by caogia** [martin-ger/esp_wifi_repeater#326]
Hi, 
I got a problem with physic mode, it always in g mode
I set it to mode 3 (n mode) and it does say 

> Phy mode setting successful

> 
But still when I check in CMD, it just g mode. and the strength only 54Mbps.
So is this a problem or my module get Problem?
----
My ESP is ESP8266MOD NodeMCU.
thanks

**Comment by martin-ger** [comment]
That's normal: in STATIONAP mode the ESP8266 can only work in g mode. I once added this option on user demand (basically for downgrading to b, which might result in longer range).  In fact, I don't see that advantage - so it is there just for completeness...
