### ISSUE TITLE
Any one knows where i change the baudrate

### ISSUE THREAD

**Issue by juliogzz** [martin-ger/esp_wifi_repeater#335]
I already looked for it and I ship it and I do not give, if anyone knows I would appreciate it very much

thanks =)

**Comment by martin-ger** [comment]
It is a constant in the code:

https://github.com/martin-ger/esp_wifi_repeater/blob/master/user/user_main.c#L4249

**Comment by juliogzz** [comment]
tks i found it last night thankyou, im forget to save the place XD
