### ISSUE TITLE
New firmare with MQTT V 3.1.1

### ISSUE THREAD

**Issue by roboticboyer** [martin-ger/esp_wifi_repeater#35]
In the branch ESP uMQTT Broker could you upgrade the pre-compiled firmware so it supports MQTT protocol version v3.1.1?

The ESP MQTT client libraries now all support the version 3.1.1 and it isn't easy or it's impossible to use the V 3.1 

Thank you

**Comment by martin-ger** [comment]
Latest commit is default MQTT v 3.1.1.

**Comment by roboticboyer** [comment]
Thank You
The new firmware is working with the Arduino MQTT libraries using V 3.1.1

**Comment by roboticboyer** [comment]
I have written an article about my test with your library and the ESP8266 uMQTT Broker :
[http://wp.me/p4ZDu-3s](http://wp.me/p4ZDu-3s)

**Comment by TridentTD** [comment]
#roboticboyer
Do you mind writting an article about  MQTT Client on uMQTT Broker ?
Thank you .

MQTT_CLIENT recompiled by 
[here](https://github.com/martin-ger/esp_wifi_repeater/blob/uMQTT_broker/user/user_config.h#L79)

**Comment by martin-ger** [comment]
The current MQTT-Client functionality is NOT a MQTT bridge or something like that. Currently it only reports the internal status of the Router(Repeater) to an MQTT-broker. That is probably not what would you expect/need...

 

A bridge-functionality can be added separately: to publish local topics to an external broker is fairly easy. Subscribing external topics to republish them locally would require an additional config API. Not to mention mapping and renaming of topics (what e.g. a Moquitto Bridge can do).

 

Cheers,

Martin

 

Von: TridentTD [mailto:notifications@github.com] 
Gesendet: Mittwoch, 24. Mai 2017 07:07
An: martin-ger/esp_wifi_repeater
Cc: martin-ger; State change
Betreff: Re: [martin-ger/esp_wifi_repeater] New firmare with MQTT V 3.1.1 (#35)

 

#roboticboyer
Do you mind writting an article about MQTT Client on uMQTT Broker ?
Thank you .

MQTT_CLIENT recompiled by
here <https://github.com/martin-ger/esp_wifi_repeater/blob/uMQTT_broker/user/user_config.h#L79>
