### ISSUE TITLE
Controlling the device connected to esp wifi repeater via the main network 

### ISSUE THREAD

**Issue by koloksk** [martin-ger/esp_wifi_repeater#355]
Hello, is it possible to control the device connected to esp8266 wifi repeater by phone / computer connected to the router (main network) as in the attached picture (orange line)?
![Bez tytułu](https://user-images.githubusercontent.com/34625628/66707821-566dad00-ed47-11e9-9aa5-d30dff8f515d.png)

**Comment by Gisbert1** [comment]
Hi Koloksk,

this works using portmapping on the ESP router, please check the readme, there you find how it works.
Additionally I have installed a static route on my main router to the IP network of the ESP router. Not sure whether this is necessary but it works.

Best Regards
Gisbert​

**Comment by koloksk** [comment]
Thanks, it works.
