### ISSUE TITLE
Daisy chain repeater (or even a mesh) within a single network 

### ISSUE THREAD

**Issue by zlewe** [martin-ger/esp_wifi_repeater#359]
I was wondering if it is possible to chain multiple esp8266 together so that every device connected to them would be in the same LAN eg. with ip = 192.168.0.X, (and therefore they can communicate with each other). Since I do not need internet so I guess  NAT can be disabled? I'm not really familiar with networking.

I read it is possible to do this by daisy chain routers with cable and disabling DHCP servers on all routers except the main one.

**Comment by martin-ger** [comment]
As the esp_wifi_repeater doesn't work as a real layer 2 repeater, there is currently no way to have the same IP subnet on the AP and the STA interface. I.e. you need IP routing or NAT.
