### ISSUE TITLE
a comment CMD would be nice

### ISSUE THREAD

**Issue by mahesh2000** [martin-ger/esp_wifi_repeater#376]
hi, i'm keeping a "command history" of the setup for the each of the ESP8266 repeaters, basically scripts. It would be great to have comments, say beginning with #, // or !, that give some context to the commands in the scripts. I could then just run the script on every new device. 

i can still do it right now -- anything that starts with #, // or ! results in an error, which, functionally, is ok -- but it'd be nice to not get the error message.

thanks for a really cool piece of software.

**Comment by martin-ger** [comment]
Just added comments: any part of a command line input after a single "#" until the end of the line will be treated as a comment and will be ignored.
