### ISSUE TITLE
How to use as a MQTT-Client mode?

### ISSUE THREAD

**Issue by TridentTD** [martin-ger/esp_wifi_repeater#39]
In file "user_config.h"  I set

#define MQTT_CLIENT 	1

After recompiled and flashing rom, 
my esp8266 connected to host is address 192.168.43.50
and I set   mqtt client mode as the following command

>set  mqtt_host   192.168.43.10                   //* another MQTT Broker
>set  mqtt_port   1883
>set  mqtt_id       esp8266_mqtt0000123
>set   mqtt_interval  5

However on another MQTT Broker (192.168.43.10)
I can't to recieve any information by mqtt-client mode.

How to use mqtt-client mode on the rom?
Thank you.

**Comment by martin-ger** [comment]
Have a look into this: https://github.com/martin-ger/esp_mqtt

This is probably what you expected...
