### ISSUE TITLE
Long list of APs not showing right

### ISSUE THREAD

**Issue by capedra** [martin-ger/esp_wifi_repeater#4]
I have lots of APs around my area, so, whenever I scan APs around using Telnet, the first APs aren't showing up correctly. Please look at the screenshot (I erased the Mac Addresses for security reasons).

![esp_scan](https://cloud.githubusercontent.com/assets/412434/21878764/2679a518-d873-11e6-8db0-b6eb8b535790.png)

**Comment by martin-ger** [comment]
This is due to the limitation of the output ringbuffer of the console. Can be configured in user_config.h: the value of MAX_CON_SEND_SIZE (currently 300)
