### ISSUE TITLE
contains malware

### ISSUE THREAD

**Issue by polararian** [martin-ger/esp_wifi_repeater#404]
why Port 7777/tcp is open on your firmware . we all know that backdoors use this port , so you need to explain about this !!

**Comment by jackkum** [comment]
[README](https://github.com/martin-ger/esp_wifi_repeater/blob/590e464dcb673cc922e62f897b91701ec784b166/README.md)
Advanced configuration has to be done via the command line on the console interface. This console is available either via the serial port at 115200 baud or via tcp port 7777 (e.g. "telnet 192.168.4.1 7777" from a connected STA).

Use the following commands for an initial setup:

set ssid your_home_router's_SSID
set password your_home_router's_password
set ap_ssid ESP's_ssid
set ap_password ESP's_password
show (to check the parameters)
save
reset

**Comment by polararian** [comment]
alright and how to close this port ? is your project open source ?

**Comment by jackkum** [comment]
You can disable it
https://github.com/martin-ger/esp_wifi_repeater/blob/5fdca67c74f66bc5787883de78e9412378c18bba/user/user_config.h#L69

**Comment by martin-ger** [comment]
You can also dynamically change or disable this port:

- set config_port portno: sets the port number of the console login (default is 7777, 0 disables remote console config)

**Comment by polararian** [comment]
could you explain more about how to disable ports and enable them , and tell me is it possible to change the frontend of config page (192.168.4.1) ?

**Comment by RibeiroSantos** [comment]
I suggest you to first read all documentation about the project. 🙂

A quarta, 17/06/2020, 12:33, polararian <notifications@github.com> escreveu:

**Comment by polararian** [comment]
i could not find anything about setting password on telnet or ssh , could you tell me the command ?
😉

**Comment by martin-ger** [comment]
There is non password other than the "lock" password.

- lock [password]: saves and locks the current config, changes are not allowed. Password can be left open if already set before (Default is the password of the uplink WiFi)
- unlock password: unlocks the config, requires password from the lock command

**Comment by polararian** [comment]
i know this but i want to set ssh with username and password

**Comment by martin-ger** [comment]
No way. There is no ssh demon for the ESP8266 - at least none that I am aware of.

**Comment by polararian** [comment]
thanks for support 💎
