### ISSUE TITLE
Can't send commands to chip

### ISSUE THREAD

**Issue by ItzLarz** [martin-ger/esp_wifi_repeater#420]
I flashed my Wemos D1 Mini with Flash Download Tool. I got a new network in my Wifi settings, named MyAP. I can connect to the network and make changes via 192.168.4.1, but I can't send commands to the chip via Serial Monitor in the Arduino IDE. I know it's the right COM, because if I join or leave the MyAP network i get this message: "station: [mac address of my smarthphone] join, AID = 1". If i just send "help" or another command, nothing happens. Am I doing something wrong?

Update: It looked like I could send changes from 192.168.4.1, but if I change the values, they don't save on the chip.

(Issue #420, nice)

**Comment by martin-ger** [comment]
Check your serial - should work. Might try via telnet 192.168.4.1 7777 should work as well.

**Comment by ItzLarz** [comment]
I think I know what the problem is, I just downloaded Mobile Telnet on my phone and it worked! I think it's because of my Norton Firewall and that it doesn't let my pc connect with an open network.

**Comment by ItzLarz** [comment]
Thank you for the help!
