### ISSUE TITLE
Question: Automesh without root node

### ISSUE THREAD

**Issue by tiago156** [martin-ger/esp_wifi_repeater#428]
Hello,

first of all thanks for the effort implementing this repeater.

I'm trying to find a solution for the following problem:

If I have dozens of trucks moving around a big field, and I need to create a automesh between the neighbors as they park together without any root node, just to create connectivity between them and allow another device to "talk"to each other using this mesh.

Basically every time that a group of 2 or more equipments get together a new mesh is "born" allowing another device to communicate through it.

![image](https://user-images.githubusercontent.com/808568/101840791-89febf80-3b23-11eb-9b1a-bde6be0b8b18.png)

Can I achieve this behavior on the current development state? If not do you think is feasible to patch it to create this behavior?

Thanks in advance.

**Comment by martin-ger** [comment]
Probably not. The "automesh" feature always requires a fixed root node, it forms a tree-like structure and the devices can only talk towards the root and via the root to the internet, not directly with each other.

Depending on your actual application you might have a look at https://github.com/gmag11/painlessMesh
