### ISSUE TITLE
Can't change phy_mode to 1

### ISSUE THREAD

**Issue by Wunderwaffez** [martin-ger/esp_wifi_repeater#434]
When I try to change the **phy_mode** 802.11**n** to 802.11**b** it resets itself and I lose connection. I both tried **telnet** and **serial port.**

**Comment by martin-ger** [comment]
Maybe your uplink AP doesn't support 11b any more? There is no good reason to use it, if you have 11g or 11n.

**Comment by Wunderwaffez** [comment]
I'm using a old router and it seems it supports it. I just wanted to change it to increase TX and RX performance.

**Comment by iansun2** [comment]
turn off ap mode before change the phy_mode seems work
