### ISSUE TITLE
Command to stop message "no ssid found, reconnect after 1s" or increase time to next retry

### ISSUE THREAD

**Issue by RibeiroSantos** [martin-ger/esp_wifi_repeater#47]
It is possible add a command to allow stop showing the message "no ssid found, reconnect after 1s", or increase the delay time,  when connect by serial at first time? Because it's a bit difficult to type with the message allways scrolling.
Thanks a lot,

**Comment by martin-ger** [comment]
set auto_connect 0
save
reset

does the job. Alternatively, if you want it as default, change the default in user_config.c to 0.
If the config is done you shout re-enable the auto_connect.
