### ISSUE TITLE
code compilation for esp32 esp-idf

### ISSUE THREAD

**Issue by Mrivilla** [martin-ger/esp_wifi_repeater#475]
Hi dears,
I show the esp nat project, but I'm interested in the automesh in this project. It would be possible to compile this project in esp-idf for ESP32?

Thanks in advance.
Marcos.

**Comment by martin-ger** [comment]
No, it is only implemented in the ESP8266 version. The code is substatially different due to the differences in the SDKs.

**Comment by Mrivilla** [comment]
Thanks Sir.
It will be a good exercise for me refreshing my programming.
Regards.
