### ISSUE TITLE
question ssid and or feature

### ISSUE THREAD

**Issue by Geekynooby** [martin-ger/esp_wifi_repeater#48]
Hi iam new to all this.. but you did a fine tutorial and work:)

I have two questions. 
Is it possible if you set ssid to ad a space in middler of the ssid ? What happens now is ( set ssid my wifi ) for example, after save and reset it only tries to connect to "my" instead of "my wifi " cant find no solution so far on the web, or is this impossible ? 

Other question more a feature: Wpa Enterprise with WPA/WPA2, EAP-PEAP, MSCHAPV2, for networks with and without certificate and user name and password? Would be neat but  think a little difficult.

Keep up the good stuff

thx

**Comment by martin-ger** [comment]
Hi,

good news: both is already done: spaces in the SSID can be quotet using the '\' character. For "my wifi" write:
`set ssid my\ wifi`

WPA Enterprise have a look into https://github.com/martin-ger/esp_peap_psk 
It is a wild hack, but currently the only way to do it, if the outer ID string is not ignored from the network.

**Comment by Geekynooby** [comment]
Whoow thats fast:) 

Ty very much gonne look it up 

Tia
