### ISSUE TITLE
Add support for WPA2 enterprise

### ISSUE THREAD

**Issue by jadolg** [martin-ger/esp_wifi_repeater#56]
It would be desirable to have support for this WPA2 enterprise and wpa_suplicant is compatible already.
Maybe this can help? https://www.hallgeirholien.no/post/esp8266-eap/

**Comment by martin-ger** [comment]
In fact, I already did some experiments with WPA Enterprise here: https://github.com/martin-ger/esp_peap_psk

It works, but WPA enterprise requires a lot of memory, so the full functionality doesn't fit in. Also, the outer authentication is hardcoded in the lib.

**Comment by Seshpenguin** [comment]
I would also like to see this added.

**Comment by martin-ger** [comment]
As said above: basic functionality is here: https://github.com/martin-ger/esp_peap_psk
Anything beyond suffers from available memory.

**Comment by Seshpenguin** [comment]
OK thanks!
