### ISSUE TITLE
Web server

### ISSUE THREAD

**Issue by Seshpenguin** [martin-ger/esp_wifi_repeater#57]
Hi,
Is it possible to run a website on the ESP alongside the NAT Router (So people connected to the ESP can access the website)?
Thanks!

**Comment by martin-ger** [comment]
Canon be done. The commandline interface can be replaced by a web server. Feel free to start a branch...

**Comment by Seshpenguin** [comment]
Do you know how I should go about implementing it?

**Comment by martin-ger** [comment]
This could be a good starting point: https://github.com/Spritetm/esphttpd. However, some experiments with the open-sdk would be helpful too.

**Comment by Seshpenguin** [comment]
Hm.. I tried a bit but sadly I don't have enough knowledge of low-level C :stuck_out_tongue: 
Maybe someone else can try to implement a webserver??

**Comment by martin-ger** [comment]
Added a basic web config interface (Thanks to rubfi).
