### ISSUE TITLE
No AP after flashing NodeMCU

### ISSUE THREAD

**Issue by antonioag95** [martin-ger/esp_wifi_repeater#64]
After flashing my NodeMCU with the tool and with options as can be seen in the image, no AP shows up. I've tried several times also by using esptool.py from Windows but same result. Where am I wrong? I've also checked if sha1 matched and they did. Thank you for your hard work!
![image](https://user-images.githubusercontent.com/30556866/28747419-61d61372-749e-11e7-94ad-0c031a057d60.png)

**Comment by karawin** [comment]
Try DIO spi mode. Some non AI-THINKER esp need DIO only.

**Comment by martin-ger** [comment]
Did you try the 1.5.4 firmware? What do you see on the serial port after reset?

**Comment by antonioag95** [comment]
I also tried 1.5.4 firmware but it didn't work. When I reset it from serial I can see "csum err" and "ets_main.c". The vendor of non-working version of the board is "Hysiry" so there must be something different in this version. After several hours, I tried with another ESP8266 (there is no vendor written on it) and 1.5.4 is perfectly working on this board.

**Comment by martin-ger** [comment]
Guess a problem with a faulty flash mem. Don't think it an issue of the software.

**Comment by antonioag95** [comment]
I don't really think it is an hardware problem because the board is okay with Arduino IDE. Anyway, on a YouTube video which is related to your great software, someone commented saying he had to flash with the official NodeMCU Flasher in order to get it work but I don't really know the options there

**Comment by karawin** [comment]
Do you hear me?
Try DIO spi mode. Some non AI-THINKER esp need DIO only.

Hysity needs the DIO spi mode.

Trust me, I encountered the problem for a user of my project.

**Comment by antonioag95** [comment]
Thank you for your help, I can confirm that using DIO spi mode correctly flashed this board with 1.5.4 firmware (the other one didn't work). I suggest writing something about these particular boards in the readme file. Keep up the good work!
