### ISSUE TITLE
Not working on NodeMCU v2 ESP8266

### ISSUE THREAD

**Issue by Rammelkast** [martin-ger/esp_wifi_repeater#66]
Tried to flash it with both 1.5.4 and normal binaries, flashing goes good and gives no errors.
However, the "MyAP" network does not show up. 

Help me :S

**Comment by martin-ger** [comment]
What does the serial console show after reboot?

**Comment by antonioag95** [comment]
As you can see I had the same problem. As suggested here I resolved by flashing 1.5.4 firmware with the option "DIO" in SPI mode.

**Comment by Rammelkast** [comment]
What do you mean with "in SPI mode"? @antonioag95

**Comment by Rammelkast** [comment]
Never mind, got it working thanks to @antonioag95!
