### ISSUE TITLE
Set WiFi Mode

### ISSUE THREAD

**Issue by dan2wik** [martin-ger/esp_wifi_repeater#68]
I was wondering if you could add the ability to change the wifi mode to b/g. N isn't possible in AP mode.

It is done in the 'arduino' SDK using "wifi_set_phy_mode(PHY_MODE_11[B|G|N])".

**Comment by martin-ger** [comment]
It is b/g anyway, as n is also impossible in StationAP mode.

**Comment by dan2wik** [comment]
But I mean set b or g. b has a higher range with it's higher TX power, and g has higher speeds.

**Comment by dan2wik** [comment]
Forcing 802.11B mode allows the repeater to transmit at a higher strength, 20.5 dBm, and reach further.
I believe it defaults to 802.11G mode which transmits at 17dBm.

**Comment by martin-ger** [comment]
Okay, convinced... added it in the latest version of the master branch.
