### ISSUE TITLE
Captive portal

### ISSUE THREAD

**Issue by nikraupp** [martin-ger/esp_wifi_repeater#69]
Hello, I'm Brazilian, I do not speak English very well ... I want to repeat the signal from my WIFI and implement a captive portal in my repeater(nodemcu). Could you help me?

**Comment by martin-ger** [comment]
enaon did a port of the NAT functionality to NodeMCU at https://github.com/enaon/nodemcu-firmware-router/tree/1.5.4.1-final-napt-ipfwd-apdns . This is probaboy what you are looking for. Captive portal functionality is not included as far as I understand...

**Comment by nikraupp** [comment]
Is it possible to do with esp8266 as a WIFI repeater on Arduino?

**Comment by martin-ger** [comment]
No, it requires the esp-open-sdk for compilation, not the Arduino IDE.
