### ISSUE TITLE
How come 'ip_napt_enable()' isn't called?

### ISSUE THREAD

**Issue by hoonkai** [martin-ger/esp_wifi_repeater#71]
AFAIK, 'ip_napt_enable()' enables NAPT for an interface, but how come it isn't called at all? Instead, it sets the value using `nif->napt = nat?1:0;` (https://github.com/martin-ger/esp_wifi_repeater/blob/master/user/user_main.c#L459)

**Comment by martin-ger** [comment]
This does the same. ;-) As I know the interfaces and manipulate the structures anyway for the input functions I can do this directly.
