### ISSUE TITLE
ESP mac address --> mqtt prefix need %02x in os_sprintf ?

### ISSUE THREAD

**Issue by giovannicandotti** [martin-ger/esp_wifi_repeater#72]
in file "user/config_flash.c" line 64 -->   os_sprintf(config->mqtt_id,"%s_%02x%02x%02x", MQTT_ID, mac[3], mac[4], mac[5]);

mind the <zero> in "%02x" to manage mac address with "0x:" parts

**Comment by martin-ger** [comment]
Thanks - added this with the latest commit.
