### ISSUE TITLE
Arduino IDE

### ISSUE THREAD

**Issue by suhaimiannuar** [martin-ger/esp_wifi_repeater#73]
May I know, if there is any way to use Arduino IDE in order to flash the ESP8266 with the files provided? Kindly please help. 
Thank you.

**Comment by martin-ger** [comment]
Sorry, I have no experience with that. The flashing tool is somewhere integrated in the IDE. Perhaps anybody else knows...?
But the usual flashing tools for the ESP work well with the binaries.
