### ISSUE TITLE
How to edit esp v. 2.1.0 's Makefile for building esp_wifi_repeater ?

### ISSUE THREAD

**Issue by TridentTD** [martin-ger/esp_wifi_repeater#90]
I want to build esp_wifi_repeater by esp-sdk v2.1.0.
But I don't know how to edit esp-sdk v2.1.0's  Makefile.

Do you mind to give esp-sdk v2.1.0's  Makefile ?

Thank you.

**Comment by martin-ger** [comment]
Just set
VENDOR_SDK = 2.1.0
in line 13 of https://github.com/pfalcon/esp-open-sdk/blob/master/Makefile .

**Comment by TridentTD** [comment]
Thank you very much. :  )
